### ISSUE TITLE
Reinstalling FTB modpack pauses indefinitely to wait for input

### ISSUE THREAD

**Issue by JoshuaWalsh** [parkervcp/eggs#208]
Please fill out the information bellow and remove from the line up
If you just submit a bug with no info I will close out your bug.
---------------

Panel Version: 0.7.13
Daemon Version: 0.6.12
Service: feed-the-beast
Modified: no

Expected Behavior:

I changed the version number of my feed-the-beast server and then used the "Reinstall Server" button in the Manage tab. I expect this to reinstall the server with the new version I've specified.

Actual Behavior:

I left the installation running for 10 minutes (longer than it usually takes) and then checked the server logs.

```
The base URL is https://www.feed-the-beast.com/projects/ftb-builders-paradise/files
ID: 2713666
SECONDURL: https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2713666
GOOD_ID: 2713669
Download_URL: https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2713669/download
Executing curl -L https://www.feed-the-beast.com/projects/ftb-builders-paradise/files/2713669/download -o ftb-builders-paradise.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  186M  100  186M    0     0  4882k      0  0:00:39  0:00:39 --:--:-- 5187k
Archive:  ftb-builders-paradise.zip
replace changelogs/1.1.0.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:
```

It appears that the `unzip` command is prompting for user input, which I am unable to provide.

Steps to Reproduce: 

1. Create an FTB server. Use any modpack that has more than 1 version. (I used ftb-builders-paradise) Choose a version other than the newest one (e.g. 1.2.0)

2. Wait for the installation to complete.

3. Change the version in the Startup tab to a newer version (e.g. 1.3.0)

4. In the Manage tab, click Reinstall Server

5. Observe that the installation does not complete successfully

**Comment by parkervcp** [comment]
I just need to change it to unzip forcing and overwrite then.

This will be destructive though as it will overwrite changes to any configs that a person has made.

**Comment by JoshuaWalsh** [comment]
I was planning on submitting a PR, we just need to add the `-o` flag to unzip.

**Comment by parkervcp** [comment]
Yeah I just pushed a branch with a fix. I need to PR it over now.

**Comment by parkervcp** [comment]
Yeah I just pushed a branch with a fix. I need to PR it over now.

**Comment by JoshuaWalsh** [comment]
Thanks! This causes the install script to succeed, but sadly the server still doesn't start correctly. I'll keep working on it and submit a PR for the rest later.

**Comment by parkervcp** [comment]
I think I will sit on this now that it has been announced that FTB is leaving curse/twitch for the most part. 

I do have a curse/forge generic egg that is probably well fir for this entire setup honestly.
