### ISSUE TITLE
ARK egg stuck on "Starting"

### ISSUE THREAD

**Issue by SubtypeZero** [parkervcp/eggs#23]
After recent updates (exact time unknown, since I had my ARK server shut down for a while), my ARK server has been getting stuck on "Starting" and doesn't change when the "Stop" button is pressed, so I have no way of knowing if the server is actually stopping. I've been shutting it down to apply updates by killing the server, so I'm hoping this can be sorted out relatively soon.

**Comment by parkervcp** [comment]
This has been fixed with https://github.com/pterodactyl/panel/pull/1224

**Comment by xZToxicZx** [comment]
I'm still getting this issue on the most recent version also the panel update you referenced had no commets for ARK
