### ISSUE TITLE
Arma 3 Egg spits out error can't start the server

### ISSUE THREAD

**Issue by rhys19** [parkervcp/eggs#94]
Panel Version: (version number) 0.7.9
Daemon Version: (version number) 0.5.6
Service: (minecraft/factorio/etc) Arma 3
Modified: (yes/no) (did you add or change things, this includes startup configs/install scripts/variables)
no
Expected Behavior:
Run the arma 3 server
Actual Behavior:
spits out an error on console
```
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 68M / 10000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server container started. Attaching...
:/home/container$ ./arma3server -ip=0.0.0.0 -port=2302 -cfg=cfg.cfg -config=config.cfg -mod= -serverMod=
/entrypoint.sh: line 17: ./arma3server: No such file or directory
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 127
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Attempting to reboot server now.
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 68M / 10000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server container started. Attaching...
:/home/container$ ./arma3server -ip=0.0.0.0 -port=2302 -cfg=cfg.cfg -config=config.cfg -mod= -serverMod=
/entrypoint.sh: line 17: ./arma3server: No such file or directory
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 127
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.
```
Steps to Reproduce: (Step by step what to do to cause the issue)
start the server

**Comment by parkervcp** [comment]
Considering your egg is only 68 megs I am going to assume it's a failed install and not the server itself.

**Comment by rhys19** [comment]
how would i fix that?

**Comment by parkervcp** [comment]
reinstall the server.

**Comment by rhys19** [comment]
pterodactyl or what?

**Comment by rhys19** [comment]
i tried reinstalling the arma server but it won't complete:

![image](https://user-images.githubusercontent.com/30848481/47469412-6bfc6680-d7c6-11e8-9a2a-8314d234d39d.png)
i've tried creating two servers

**Comment by parkervcp** [comment]
Please get the install logs for the server. `/srv/daemon/config/servers/<server-uuid>/install.log`

**Comment by rhys19** [comment]
ah i fixed the installing part it was emailing me my steam guard code :D  now just need to fix the starting issue

**Comment by rhys19** [comment]
now it looks like it's installing server files ```[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/mnt/server/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Logging in user 'steamguy283' to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.34 (18931241 / 5604404710)
 Update state (0x61) downloading, progress: 0.69 (38746885 / 5604404710)
 Update state (0x61) downloading, progress: 1.28 (71823851 / 5604404710)
 Update state (0x61) downloading, progress: 1.86 (104329875 / 5604404710)
 Update state (0x61) downloading, progress: 2.35 (131595128 / 5604404710)
 Update state (0x61) downloading, progress: 2.87 (160593552 / 5604404710)
 Update state (0x61) downloading, progress: 3.40 (190279694 / 5604404710)
 Update state (0x61) downloading, progress: 3.90 (218680679 / 5604404710)
 Update state (0x61) downloading, progress: 4.37 (245050157 / 5604404710)
 Update state (0x61) downloading, progress: 4.87 (273138818 / 5604404710)
 Update state (0x61) downloading, progress: 5.40 (302774702 / 5604404710)
 Update state (0x61) downloading, progress: 5.99 (335455937 / 5604404710)
```

**Comment by ryan1161** [comment]
I have striped out everthing and add the files from what the wiki said to setup them as and still getting this error at the entrypoint.sh from the docker image. 
![image](https://user-images.githubusercontent.com/2374149/47532190-44180c00-d875-11e8-8088-7f0f70c7bf8a.png)

**Comment by rhys19** [comment]
basically the same issue i'm having ;)

**Comment by rhys19** [comment]
which yet still needs to be fixed lol

**Comment by parkervcp** [comment]
I am looking into this when I can. I found some issues with something else while setting up a new server for this.

**Comment by rhys19** [comment]
that's fine i'd just like to get it up on the panel when it gets fixed :D

**Comment by parkervcp** [comment]
It's weird because my install works fine.

**Comment by parkervcp** [comment]
I literally cannot re-create this issue, I even spun up a new panel and daemon on a separate host.

@rhys19 I need to know what OS the host is on.
@ryan1161  What version of the daemon are you on? I also need to know what base OS the host is running.

**Comment by parkervcp** [comment]
Kernel version too  please.

**Comment by rhys19** [comment]
Ubuntu 18.04 Hosted off of digital ocean (Kernel version: unknown)

**Comment by rhys19** [comment]
my daemon has updated files but won't show updated version under the node for some reason. and i even restarted the whole vps too so idk.

**Comment by rhys19** [comment]
any update parker? cause i can try to install my panel on a local vps and see if it's digital ocean

**Comment by parkervcp** [comment]
I have fired up a VPS and tried to re-create this issue with both CentOS 7 and Ubuntu 18.04. I can't get it to fail.

**Comment by parkervcp** [comment]
If you guys want I can create logins on my testing server so you can see.

**Comment by rhys19** [comment]
no it's ok i believe you i'll run a ubuntu 18.04 vm on my esxi server i have built at my house to see if it's digital ocean i'll report back if it does or doesn't work

**Comment by rhys19** [comment]
i have switched from [Digital Ocean](https://digitalocean.com/) to [Vultr](https://vultr.com/)

i am installing the panel on a new ubuntu 18.04 VPS with nothing else on it to see if it will work if it does this can be closed but if it doesn't i'll let you know!

**Comment by rhys19** [comment]
just got the panel installed and installing arma server now :D

**Comment by rhys19** [comment]
hmm 
![image](https://user-images.githubusercontent.com/30848481/47833273-ddf52280-dd67-11e8-9cb3-4b54d6a63215.png) 

same thing for some reason :(
i paid $15 for another ubuntu 18.04 vps.
ugh :(

**Comment by parkervcp** [comment]
I set up an hourly vps on vultr for so I could test. I am also shelling out cash to try and make this happen as well. Don't try and complain about money issues here. You didn't have to get a whole month of vps.

**Comment by rhys19** [comment]
i'm not complaining i am just saying. but i also have needs for the vps aswell. ;)

**Comment by rhys19** [comment]
i actually like vultr better then DO because their support team is way better.

**Comment by rhys19** [comment]
question what os is your vps then i'll try it.

**Comment by parkervcp** [comment]
I tried both CentOS 7 and Ubuntu

**Comment by parkervcp** [comment]
I tried both CentOS 7 and Ubuntu 18.04

**Comment by rhys19** [comment]
hm interesting. i wonder why i'm getting this!

the steps i did after installing ubuntu 18.04 was:

1. Install Pterodactyl from https://pterodactyl-guides.readme.io/docs/ubuntu1804-panel-07
2. Updated it.
3. made a new nest called Arma 3
4. imported the arma 3 egg
5. created the arma 3 server from the arma 3 egg
6. run it.
7. Error happens.

^
That's what i did to get the error

**Comment by rhys19** [comment]
any idea if i did anything wrong? maybe the setup or something

**Comment by HorlbogeDE** [comment]
Im having the exact same issues.
Kernel: 4.15.0-33-generic
OS: Ubuntu 18.04.1
Log from Pterodactyl:
`/entrypoint.sh: line 25:    16 Segmentation fault      (core dumped) ./arma3server -ip=0.0.0.0 -port=25000 -cfg=cfg.cfg -config=config.cfg -mod= -serverMod=`

Disk usage is at 5674MB, the Installer runs fine (after disabling steam guard).

**Comment by HorlbogeDE** [comment]
Im having the exact same issues. Arma installed fine after disabling steamguard (Size over 5 gig, so should be good), but Starting results in an error:
`/entrypoint.sh: line 25:    16 Segmentation fault      (core dumped) ./arma3server -ip=0.0.0.0 -port=25000 -cfg=cfg.cfg -config=config.cfg -mod= -serverMod=`

OS: Ubuntu 18.04.1
Kernel: 4.15.0-33-generic
Virtualized: Yes, KVM (4 Cores, 8GB RAM - running on my own host)

**Comment by rhys19** [comment]
does it work/startup after disabling steam guard @HorlbogeDE

**Comment by HorlbogeDE** [comment]
@rhys19, as I said, I was able to install Arma via the agg after diabling steam guard. The server is not able to start.

**Comment by CptCunningham** [comment]
Same error here as well, steps to error are the same as @rhys19 . 

Using Ubuntu 16.04.

**Comment by parkervcp** [comment]
Again. I literally cannot recreate these issues. I have tried new vps setups and it has yet to fail. I can set up a panel and daemon for you all to set up servers on and test. I still see no reason as to why it's failing.

**Comment by rhys19** [comment]
does it start? because if it does i'll do some internal testing to my vps to see if i can get it to work

**Comment by rhys19** [comment]
also did u use the pterodactyl documentation for vultr or use vultr's guide?

**Comment by rhys19** [comment]
i did add a variable for steam guard and crap if you want to test it to see if it's that. i'll export the egg with the variable and send it.

**Comment by rhys19** [comment]
i'm trying it on my account that i don't have anything on (steam account) and has steam guard disabled. with a new install of Pterodactyl.

**Comment by rhys19** [comment]
this is the pic of the egg cfg: 
![image](https://user-images.githubusercontent.com/30848481/47955707-da30ee00-df69-11e8-909a-328e03a0b760.png)

**Comment by rhys19** [comment]
i just found out if you change the startup from `./arma3server "-port={{SERVER_PORT}}" "-cfg={{CFG}}" "-config={{CONFIG}} {{CUSTOM}}" "-mod={{MODS}}" "-serverMod={{SERVERMODS}}"`
to `bash arma3server "-port={{SERVER_PORT}}" "-cfg={{CFG}}" "-config={{CONFIG}} {{CUSTOM}}" "-mod={{MODS}}" "-serverMod={{SERVERMODS}}"`

then it says:
```
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 5696M / 4294967295M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
[Pterodactyl Daemon] Server container started. Attaching...
:/home/container$ bash arma3server -port=2302 -cfg=cfg.cfg -config=config.cfg -mod= -serverMod=
arma3server: arma3server: cannot execute binary file
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 126
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Server marked as OFF
```
am i getting somewhere? lol

**Comment by dikkatdeli** [comment]
Using Ubuntu 16.04.

I have same error too.

/entrypoint.sh: line 25: 16 Segmentation fault (core dumped) ./arma3server

**Comment by dikkatdeli** [comment]
> Try clearing the startup parameters so there are no empty ones and make sure the files it tries to find exist.

checked everything you said. That's not the problem.

**Comment by Getenk** [comment]
I have that problom too

**Comment by parkervcp** [comment]
I get that it's a widespread issue but I have no idea why.

**Comment by elRazer** [comment]
same problems
OS: Debian 9
Kernel: 4.9.0-9-amd64
/entrypoint.sh: line 25: 16 Segmentation fault (core dumped) ./arma3server -ip=0.0.0.0 -port=2302 -cfg=cfg.cfg -config=config.cfg -mod= -serverMod=
installer works fine but this error occurs on startup

**Comment by rhys19** [comment]
@parkervcp is it possible that you don't have your empty parameters nulled/Empty? that could be the case but i'm not so sure.

**Comment by parkervcp** [comment]
I have empty mods and server mods

**Comment by parkervcp** [comment]
So some testing from AreYouScared on discord has found that using my dockerized daemon works fine running the server. This gives me something to narrow down on.

**Comment by metallicgloss** [comment]
I had the same problem that previous people did in this issue (the core dump, not file not found). The command that Pterodactyl was trying to run resulted with a core dump when running through docker, but running it directly on the host node worked perfectly.

If it helps you to attempt to resolve the problem, I was able to correct the problem for myself on all nodes with the core dump problem by using a modified docker container. It was forked originally from Nurdism and is actually the container that myself and @Yomanz used and adjusted initially when testing this egg. 

Quay build: http://quay.io/metallicgloss/arma3-image:master
GitHub Container: https://github.com/Yomanz/Containers/tree/rvr4

Other than some extra fancy adjustments at the bottom of the container, it is similar to the standard source container but has allowed me to get the problem fixed and resolved.

**Comment by parkervcp** [comment]
@metallicgloss With testing we have found that running my daemon container makes the server run fine with the source image. I am not sure what is causing this but I am working on getting it working normally.

**Comment by metallicgloss** [comment]
That's fine, not sure what exactly the difference is between them but with the default source one, the core dump is present but with the rvr4 one it doesn't occur.

**Comment by rhys19** [comment]
if tessting needs to be done then let me know ;) sorry i haven't posted in a bit got stuff irl like my mother is in the hospital so i'm trying to atleast get done what i can do to get her back. she has no immune system so i have to keep the house clean. but in the meantime i'm trying what i can do to get this to work.

**Comment by Jabbers99** [comment]
I'm also having this issue.

**Comment by parkervcp** [comment]
This should be resolved in https://github.com/parkervcp/eggs/commit/93733e84235e9af8207f12669a7b301a0a935eda

**Comment by Arcanum417** [comment]
Well I might be having a related problem.
`/entrypoint.sh: line 30: 14 Segmentation fault (core dumped) ${MODIFIED_STARTUP}`

**Comment by ScottUK** [comment]
I'm also having the same problem, have tried re-installing the panel.

`/entrypoint.sh: line 30: 14 Segmentation fault (core dumped) ${MODIFIED_STARTUP}
PTDL_CONTAINER_ERR: There was an error while attempting to run the start command.`

**Comment by parkervcp** [comment]
Can you at least offer the entire startup and not just the failure line @ScottUK

**Comment by Arthur-G** [comment]
~/server: ./arma3server -ip=0.0.0.0 -port=25559 -cfg=basic.cfg -config=server.cfg nullable -mod=nullable -serverMod=nullable
/entrypoint.sh: line 30: ./arma3server: No such file or directory
PTDL_CONTAINER_ERR: There was an error while attempting to run the start command.

**Comment by parkervcp** [comment]
> ~/server: ./arma3server -ip=0.0.0.0 -port=25559 -cfg=basic.cfg -config=server.cfg nullable -mod=nullable -serverMod=nullable
> /entrypoint.sh: line 30: ./arma3server: No such file or directory
> PTDL_CONTAINER_ERR: There was an error while attempting to run the start command.

Your issue isn't related to this error at all...

**Comment by krille02** [comment]
I have a question where to write in your mods for the arma3 server on pterodactyl if someone can write which file you can write in all the mods so they start when you start the server and which server.cfg should you use

**Comment by QuintenQVD0** [comment]
> I have a question where to write in your mods for the arma3 server on pterodactyl if someone can write which file you can write in all the mods so they start when you start the server and which server.cfg should you use

Don't use a old issue for that come to the discord for that.
